In [1]:
import pandas as pd
import math

In [2]:
# WIN
#users_sleepy = pd.read_csv(r'C:\Users\Incognitus\Downloads\entries.csv', sep=';') 
# MAC
users_sleepy = pd.read_csv(r'/Users/vladislavlipkin/Downloads/entries.csv', sep=';')

In [3]:
# Берем нужные столбцы из исходного датафрейма
users_filter = users_sleepy.loc[:, ['user', 'dt']]

# Преобразуем столбец dt в формат datetime
users_filter['dt'] = pd.to_datetime(users_filter['dt'], format='%d.%m.%Y')

# Определяем дату первого визита (регистрации) каждого пользователя
users_filter['dt_reg'] = users_filter.groupby('user')['dt'].transform('min')

# Считаем разницу в днях между визитом и регистрацией
users_filter['diff'] = (users_filter['dt'] - users_filter['dt_reg']).dt.days

# Считаем общее количество уникальных пользователей
all_users = users_filter['user'].nunique()

# Вычисляем retention: доля уникальных пользователей в каждом diff
users_filter['retention'] = users_filter.groupby('diff')['user'].transform('nunique') / all_users * 100

# Сводная таблица: и retention, и количество уникальных пользователей
pivot = users_filter.pivot_table(
    index='diff',
    values='user',
    aggfunc='nunique'   # считаем уникальных пользователей
).rename(columns={'user': 'unique_users'}).reset_index()

# Добавляем колонку retention в тот же pivot
pivot['retention'] = pivot['unique_users'] / all_users * 100

# Создаем полный диапазон diff от min до max (чтобы не было пропусков)
full_range = pd.DataFrame({'diff': range(pivot['diff'].min(), pivot['diff'].max() + 1)})

# Объединяем полный диапазон с pivot (left join)
pivot_full = full_range.merge(pivot, on='diff', how='left')

# Просматриваем первые строки итоговой таблицы
pivot_full.head(20)

    diff  retention
0      0     100.00
1      1      51.95
2      2      52.60
3      3      52.75
4      4      51.20
5      5      48.40
6      6      49.20
7      7      46.35
8      8      47.70
9      9      47.90
10    10      47.05
11    11      44.85
12    12      43.00
13    13      43.00
14    14      25.00
15    15      24.20
16    16      25.90
17    17      23.25
18    18      23.90
19    19      22.40